# Generated by Django 4.2.4 on 2023-08-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_teachers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
